basic = {
"hi": ["Hi"],
"sup": ["Sup!"],
"how are you": ["I'm all good, you?"],
"i'm good": ["Good"],
"ball": ["Rounded!"],
"cat": ["Cute!"],
"dog": ["Barkable!"],
"flowers": ["Sniffable!"],
"castle": ["Casstle town!"],
"write a code": ["I cannot support writing a code right now. Try better versions."],
"write an essay": ["print(essay)"],
"mesmerizer": ["a wonderful song."],
"tigra": ["Cat! RIP..."],
"hard": ["Cool guy!"],
"russian": ["Да?"],
"premier": ["Of course it sucks!"],
"math": ["Not a queen of all sciences!"],
"kbtu": ["Dream!"],
"jarona": ["What a predictable creature!"],
"disco": ["Here I come san frandisco!!!"],
"ak": ["M4A1-S"],
"money": ["Nanana!"],
"tds": ["Cool game!"],
"hi!": ["HI!"],
"how are you?": ["Good! You?"],
"i am good": ["Nice!"],
"i am good too": ["Nice2x!"],
"drown": ["You should drown with me~"],
"weirdo": ["No, I'm not"],
"2+2": ["5, ofc!"],
"proceed": ["Nah"],
"basic": ["Ik im bad af ,sorry"],
"london": ["Wish I'll live there!"]


}
