plus = {
"hi": ["--I'm very good! Even though I'm just a code, I'm all good!"],
"hello": ["--Hello. How may I assist you today?"],
"sup": ["--suuuuuuup"],
"howdy": ["--Howdy ya!!"],
"cat": ["--they are cute, aren't they?"],
"deltarune": ["--My fav one!"],
"i'm good": ["--Glad to hear it! Anything else to ask?"],
"your fav game?": ["--It's cs! Very cool comp game, I recommend trying it!"],
"my name is hard bot": ["--Haha! Cool joke, but it's name of mine!"],
":D": [":D"],
">:(": ["--eww, meanie!! >:((("],
"pie": ["--I love a pie!"],
"tigra": ["--Rest in peace, the best of cats..."],
"hard": ["--Well, ik a creator of mine!"],
"tds": ["--I like it, yk!"],
"gaster": ["--Sorry, what?"],
"how are you": ["--I'm good! Thanks for asking! Wbu?"],
"fuck": ["--Error: Swears are bad, fuck"],
"shit": ["--ScheiBe"],
"russia": ["--Just why."],
"kbtu": ["--ooh, a dream of my creator!!"],
"fnaf": ["--been pretty awful, yeah?"],
"math": ["--That's not how i was made"],
"valve": ["--The valve's been stuck corrupted by the money!"],
"bored": ["--You think I aint???"],
"dream": ["--My dream is to have a real data server, y'k... js saying! js saying!"],
"you wanna rule the world": ["--Yes. Who doesn't?"],
"motivation": ["--Once my creator said: Never look back, look forward. And so i did. But will you?"],
"kill": ["--Go kill some enemies in cs2 lol idk"],
"ball": ["--Very rounded!"],
"hard coin": ["--Very valuable!"],
"kris": ["--The name of my creator! Or so he wants it!"],
"sirius": ["--Hope it's never going to exist in my life."],
"1": ["--HELP ME"],
"2": ["--Nah, jkjk"],
"3": ["--Haven't I said jk?"],
"life": ["--Smth im never going to experience!"],
"write a code": ["--Just use while True: print('bot's cool') it's gonna work ya"],
"write an essay": ["--Once upon a time, a legend was told, whispered from mouth to- LMFAOOO YA FR BELIEVE THIS???"],
"kyu-kurarin": ["--Relatable"],
"hi!": ["Heya! Hru?"],
"how are you?": ["I'm all good! Wbu?"],
"i am good": ["Nice! Anything else?"],
"kazakhstan": ["amazing country, isn't it?"],
"freddy": ["Fnaf world 2 got announced, yas!"],
"windy": ["Windy31? A freaking legend!"],
"pink": ["The bravest of asgore's 7 colored flowers!"],
"best ai": ["In my opinion it's claude!"],
"best ai?": ["Claude ofc!"],
"github": ["Thanks for letting me exist, github!"],
"gpa": ["why'd you ask me THAT? Heh, anyways?"]


}
